Prakt agile modellierung 2022
neuroevolution-ai/NaturalNets pull request #12
Opened 2022-07-18 18:49 UTC by uvlvd

2022-08-05 14:04 UTC, pdeubel requested changes
Also erstmal nicht erschrecken bei den vielen Kommentaren, ich sollte das Review sehr ausführlich machen, da ich auch selbst mit dem Code weiter arbeiten werde. Des Weiteren ist das Meiste auch Kleinigkeiten wie z.B. typos.

Falls du die GitHub Code Review Funktion noch nicht kennst, man kann beim Review Code Suggestions machen, die dann im GitHub Web Interface angenommen werden können. Das heißt du kannst die Code Suggestions die ich hier im Review gemacht habe ganz einfach im Browser annehmen (oder ablehnen), dann wird das im Code direkt übernommen als Commit (oder halt nicht falls du ablehnst).

Der Code gefällt mir sehr gut, die Klassenhierarchie ist sinnig und gibt eine gute Struktur sodass man sich schnell zurecht findet und versteht was passiert. Die Idee den State Vektor als NumPy Array zu machen, welches nur einmal allokiert ist und von den einzelnen Objekten dann verändert wird finde ich auch gut, da es (wahrscheinlich) sehr performant ist. 

# Kleinigkeiten
Wie gesagt im Großen und Ganzen hab ich folgende Kleinigkeiten gefunden:
- Beim Konkatenieren von Pfaden nutze ich persönlich lieber `os.path.join()` da es die Slashes besser handhabt, das hab ich überall wo ich es gefunden habe als Code Suggestion gemacht
- Oft hast du bei den type hints `list[Object` oder `dict[Object]` gemacht, das geht allerdins mit den built-in types `list` und `dict` nicht, da brauchst du `typing.List`, bzw. `typing.Dict` -> auch das hab ich wo ich es gefunden habe als Code Suggestion gemacht
- Die Bilddatei `img/car_configurator_show_configuration.png`: Warum ist die größer als die anderen und hat einen transparenten Rand?
- Und ein paar typos bzw. Kommentare die ich als nicht so präzise empfunden habe, hab ich leicht verändert in Code Suggestions, kannst du dir ja mal angucken

# Größeres
Ich hab auch ein paar größere Sachen:
- Bei ein paar Stellen hast du Popups (z.B. im `CarConfigurator` den `CarConfiguratorPopup`), nicht als Child der Klasse hinzugefügt -> Ich denke das war ausversehen, da dann der State der Popups nicht im gesamten State Vektor ist, oder? Die Stellen wo das war, die ich gefunden habe, hab ich kommentiert
- Generell die Anzahl der States: Ich weiß nicht was Daniel und du da besprochen habt wie das gemacht werden soll. In der originalen App wurde jede Einstellung ja doppelt genutzt, einmal wurde Code Coverage erhöht wenn die Einstellung geändert wurde, und dann nochmal wenn man im Hauptfenster mit der gewählten Einstellung den Button gedrückt hat. Das ist hier jetzt nicht so gehandhabt, sondern es wird nur der State Vektor einmal verändert wenn die Einstellung geändert wird (jedenfalls hab ich es so verstanden). Wenn das so abgesprochen wurde ist es OK, ansonsten könnte man sich überlegen den State Vektor noch zu erweitern
- Abgesehen davon muss man sich den alten State Vektor immer abspeichern und mit XOR etc. vergleichen, so wie in `test_app_time.py` gemacht. Ich weiß nicht ob das so gut ist, und das nicht irgendwie in der `step()` Funktion gemacht werden sollte, damit man als Aufrufer der Environment immer den State bekommt der aussagt wie viel von der App man schon erreicht hat und nicht den aktuellen State -> Eventuell kann man das nochmal mit Daniel besprechen
- Bezüglich des letzten Punktes ist mir auch folgendes aufgefallen: `App` folgt nicht dem Interface einer OpenAI Gym Environment, bei der wird erwartet dass `reset()` die Beobachtung returned und `step()` die Beobachtung, den Reward, das Done Signal und ein Info Objekt returned. Das fehlt noch, insbesondere die Berechnung des Rewards. Ich denke hier wäre das mit dem XOR etc. vielleicht auch sinnvoll?
- Die App wurde auch nicht in dem Framework als Environment registriert, das habe ich in Code Suggestions in `app.py` gefixed
- Der Car Configurator und Figure Printer hat kleinere Bugs/Unstimmigkeiten mit der originalen App. In den jeweiligen Hauptklassen und Settings Klassen habe ich kommentiert was mir da aufgefallen ist

Alles in allem aber ein sehr schönes Projekt und eine gute Abbildung der originalen App! Danke!

2022-08-05 14:04 UTC, pdeubel requested changes
Also erstmal nicht erschrecken bei den vielen Kommentaren, ich sollte das Review sehr ausführlich machen, da ich auch selbst mit dem Code weiter arbeiten werde. Des Weiteren ist das Meiste auch Kleinigkeiten wie z.B. typos.

Falls du die GitHub Code Review Funktion noch nicht kennst, man kann beim Review Code Suggestions machen, die dann im GitHub Web Interface angenommen werden können. Das heißt du kannst die Code Suggestions die ich hier im Review gemacht habe ganz einfach im Browser annehmen (oder ablehnen), dann wird das im Code direkt übernommen als Commit (oder halt nicht falls du ablehnst).

Der Code gefällt mir sehr gut, die Klassenhierarchie ist sinnig und gibt eine gute Struktur sodass man sich schnell zurecht findet und versteht was passiert. Die Idee den State Vektor als NumPy Array zu machen, welches nur einmal allokiert ist und von den einzelnen Objekten dann verändert wird finde ich auch gut, da es (wahrscheinlich) sehr performant ist. 

# Kleinigkeiten
Wie gesagt im Großen und Ganzen hab ich folgende Kleinigkeiten gefunden:
- Beim Konkatenieren von Pfaden nutze ich persönlich lieber `os.path.join()` da es die Slashes besser handhabt, das hab ich überall wo ich es gefunden habe als Code Suggestion gemacht
- Oft hast du bei den type hints `list[Object` oder `dict[Object]` gemacht, das geht allerdins mit den built-in types `list` und `dict` nicht, da brauchst du `typing.List`, bzw. `typing.Dict` -> auch das hab ich wo ich es gefunden habe als Code Suggestion gemacht
- Die Bilddatei `img/car_configurator_show_configuration.png`: Warum ist die größer als die anderen und hat einen transparenten Rand?
- Und ein paar typos bzw. Kommentare die ich als nicht so präzise empfunden habe, hab ich leicht verändert in Code Suggestions, kannst du dir ja mal angucken

# Größeres
Ich hab auch ein paar größere Sachen:
- Bei ein paar Stellen hast du Popups (z.B. im `CarConfigurator` den `CarConfiguratorPopup`), nicht als Child der Klasse hinzugefügt -> Ich denke das war ausversehen, da dann der State der Popups nicht im gesamten State Vektor ist, oder? Die Stellen wo das war, die ich gefunden habe, hab ich kommentiert
- Generell die Anzahl der States: Ich weiß nicht was Daniel und du da besprochen habt wie das gemacht werden soll. In der originalen App wurde jede Einstellung ja doppelt genutzt, einmal wurde Code Coverage erhöht wenn die Einstellung geändert wurde, und dann nochmal wenn man im Hauptfenster mit der gewählten Einstellung den Button gedrückt hat. Das ist hier jetzt nicht so gehandhabt, sondern es wird nur der State Vektor einmal verändert wenn die Einstellung geändert wird (jedenfalls hab ich es so verstanden). Wenn das so abgesprochen wurde ist es OK, ansonsten könnte man sich überlegen den State Vektor noch zu erweitern
- Abgesehen davon muss man sich den alten State Vektor immer abspeichern und mit XOR etc. vergleichen, so wie in `test_app_time.py` gemacht. Ich weiß nicht ob das so gut ist, und das nicht irgendwie in der `step()` Funktion gemacht werden sollte, damit man als Aufrufer der Environment immer den State bekommt der aussagt wie viel von der App man schon erreicht hat und nicht den aktuellen State -> Eventuell kann man das nochmal mit Daniel besprechen
- Bezüglich des letzten Punktes ist mir auch folgendes aufgefallen: `App` folgt nicht dem Interface einer OpenAI Gym Environment, bei der wird erwartet dass `reset()` die Beobachtung returned und `step()` die Beobachtung, den Reward, das Done Signal und ein Info Objekt returned. Das fehlt noch, insbesondere die Berechnung des Rewards. Ich denke hier wäre das mit dem XOR etc. vielleicht auch sinnvoll?
- Die App wurde auch nicht in dem Framework als Environment registriert, das habe ich in Code Suggestions in `app.py` gefixed
- Der Car Configurator und Figure Printer hat kleinere Bugs/Unstimmigkeiten mit der originalen App. In den jeweiligen Hauptklassen und Settings Klassen habe ich kommentiert was mir da aufgefallen ist

Alles in allem aber ein sehr schönes Projekt und eine gute Abbildung der originalen App! Danke!

2022-08-09 13:06 UTC, pdeubel commented on naturalnets/environments/app/main_window_pages/text_printer.py
> +    STATE_LEN = 1
Wurde besprochen

2022-08-09 13:09 UTC, pdeubel commented on naturalnets/environments/app/main_window_pages/calculator.py
> +        return self.get_state()[0]
```suggestion
    def is_open(self) -> int:
        """Returns the opened-state of this popup."""
        return self.get_state()[0]
```

2022-08-20 14:12 UTC, uvlvd commented on naturalnets/environments/app/main_window_pages/calculator.py
> +                return
Die Abfrage verhindert dass zwei Dropdowns gleichzeitig geöffnet sein können, Beispiel: erst auf Operand 1-Dropdown Klicken, dann auf Operator-Dropdown => ohne die Abfrage sind beide geöffnet.

2022-08-27 19:19 UTC, uvlvd commented on naturalnets/environments/app/main_window_pages/figure_printer.py
> +        self._rendered_figure_color:Color = None # color rendered onto the image
Wenn eine Figure gerendered wurde und dann durch die Settings `self._figure_color_from_settings` verändert wird, bleibt die ursprünglich gerenderte Farbe (bzw. auch die Figur) solange bestehen bis erneut auf den "Draw Figure" Button geklickt wird, dafür wird die momentan angezeigte Farbe als `self._rendered_figure_color` gespeichert

2022-08-27 19:47 UTC, uvlvd commented on naturalnets/environments/app/settings_window.py
> +            return
Die Abfrage existiert an dieser Stelle um zu verhindern dass bei einem offenem Dropdown/Popup in einer Settings-Page der Close-Button bzw. die Tab-Buttons des Settings-Window angeklickt werden können, der Tab handled dann den Klick auch wenn sich der Klick außerhalb des Tabs befindet und schließt u.U. das geöffnete Dropdown

2022-08-28 18:05 UTC, uvlvd commented on naturalnets/environments/app/settings_window_pages/figure_printer_settings.py
> +                                    for (checkbox, figure) in self.checkbox_to_figure.items()}
Die Mappings in beide Richtungen sind aus Effizienzüberlegungen entstanden. Das Array `figure_checkboxes` existiert weil ich nicht sicher war ob Python dicts 'insertion order preserving' sind. Prinzipiell wäre es auch möglich nur ein einzelnes dict, z.B. `checkbox_to_figure` zu verwenden und `figure_checkboxes` durch Iteration über die keys von `checkbox_to_figure` zu ersetzen. `figure_to_checkbox` wird nur von `select_figure_checkbox()` verwendet, hier müsste man dann über `figure_to_checkbox.items()` iterieren um die entsprechende Funktionalität zu erreichen.

2022-08-28 18:18 UTC, uvlvd commented on naturalnets/environments/app/settings_window_pages/figure_printer_settings.py
> +                                                           .set_selected_value(curr_dropdown_value)
Eigentlich sollte es nicht möglich sein dass an dieser stelle `curr_dropdown_value` `None` ist, da das Popup-Dropdown immer einen Wert haben müsste/soll (wird beim öffnen des Dropdowns gesetzt, kann vom Nutzer nicht auf `None` gesetzt werden). Habe deswegen statt eine Exception zu schmeißen aus dem `if` ein `assert` gemacht.

Für die letzte Zeile habe ich eine Funktion in den `figure_printer_settings` hinzugefügt.

2022-08-28 19:37 UTC, uvlvd commented on naturalnets/environments/app/widgets/dropdown.py
> +                i += 1
Die BBs werden neu gesetzt weil die BB von jedem DropdownItem davon abhängt, welche items gerade sichtbar sind. Ich habe die Funktion jetzt zum besseren Verständnis in `_update_item_bounding_boxes()` umbenannt und eine weitere Funktion `get_visible_items()` hinzugefügt, die wirklich nur die sichtbaren items zurück gibt.

2022-08-28 19:43 UTC, uvlvd commented on naturalnets/environments/app/widgets/dropdown.py
> +                item.set_selected(False)
Mit kleiner Anpassung übernommen

2022-08-28 20:01 UTC, uvlvd commented on naturalnets/environments/app/widgets/dropdown.py
> +                self.set_selected_item(item)
Ich würde die Funktion an dieser Stelle so belassen, weil sie m.M.n. die Codelesbarkeit erhöht. Wenn einfach das erste Arrayelement ausgewählt wird müsste man die Funktion umbenennen, allerdings wäre dann u.U. an den genannten Stellen in `CalculatorSettingsPopup` und `FigureCheckboxesPopup` nicht auf den ersten Blick erkennbar warum die Funktion aufgerufen wird (zumindest nicht wenn dem Leser nicht bekannt ist dass es sich um einen Sonderfall handelt, in dem nur ein sichtbares Element übrig ist).

2022-08-28 20:11 UTC, uvlvd commented on naturalnets/environments/app/widgets/dropdown.py
> +                i += 1
Das TODO weist darauf hin dass bei Wiederverwendung der Dropdown-Klasse/ erweiterung der App um weitere Dropdowns darauf geachtet werden muss, dass kein Dropdown die Bounds des MainWindows überschreitet (bzw. dass die Dropdown-Klasse eigentlich um eine Funktion ergänzt werden sollte, die überprüft ob ein weiteres DropdownItem dazu führt dass die Bounds des MainWindows überschritten werden könnten).

2022-08-31 11:30 UTC, pdeubel approved these changes
Alle gewünschten Änderungen sind eingearbeitet, danke!

2022-08-31 11:34 UTC, merged