Passlock app
neuroevolution-ai/NaturalNets pull request #24
Opened 2023-02-14 08:34 UTC by VitoVoelker

2023-02-24 12:34 UTC, pdeubel requested changes
Ich bin den Code soweit mal durchgegangen, super Projekt auch hier wieder 👍🏽 Ich bin mal gespannt wie sich diese App trainieren lässt, auch auf Grund des eher höheren Action Spaces.

Ich habe noch ein paar Sachen die mir aufgefallen sind, in unbestimmter Reihenfolge (siehe dazu auch die Kommentare die ich im Code hinterlassen habe):
- "Darkmode not implemented yet"
  - Implementierst du den noch oder ist das einfach die Funktionalität des Darkmodes hier?
- Viele Print Statements, diese müssen weg
    - Die Print Statements müssen weg, die stören später beim Training etc. Falls du sie brauchst zum Debuggen nutze logging.debug
    - Habe ich oft angemerkt, eventuell habe ich das aber auch übersehen, bitte daher selbst nochmal nachgucken und entfernen (gilt generell für meine Anmerkungen)
- In der `SignupPage` machen der Sign Up und Login Button das Gleiche, ist das gewollt?
  - Generell finde ich dass oft noch mehr Funktionalität bzw. "Reward Potential" möglich gewesen wäre, allerdings weiß ich nicht was du mit Daniel bzgl. des Umfangs der App ausgemacht hast
  - Bspw. bei den Popups reicht ein Klick irgendwo in das Popup um es zu schließen, evtl. wäre es interessanter wenn man nur den "Close" Button z.B. trifft
- Checkstyle Fixen
    - In Pycharm werden mir Checkstyle Warnings immer direkt angezeigt und dort ist es eben auch sehr einfach die zu fixen mit Autoformat. Wenn es geht würde ich dich bitten nochmal durchzugehen und solche Warnings zu fixen, dazu wenn das bei VS Code nicht automatisch angezeigt wird irgendwie einschalten, oder halt kurz PyCharm Community Edition runterladen und mit AutoFormat das machen
    - Auf jeden Fall solltest musst du die unused imports entfernen (wird auch in PyCharm angezeigt)
    - Weiteres wäre schön wie unnötige Klammern bei if's, zu viele Leerzeilen etc. (wie gesagt mit autoformat ist das sehr schnell erledigt)
- Type Hints sind nur an manchen Stellen dabei, wenn du Zeit hast wäre das schön wenn du die an möglichst vielen Stellen ergänzen könntest, besonders bei den neuen Widget Klassen die du hinzugefügt hast
- Ähnlich zum letzten Punkt ist dass du viele `handle_click()` Methoden hast, die ein bool return type haben (oder return True zurückgeben allerdings nie `return False` machen. Daher wird in solchen Fällen dann immer `None` zurückgegeben (weil kein return Statement mehr vorhanden ist. Bitte da einfach nochmal durchgehen und mit `return False` ergänzen damit immer ein bool zurückgegeben wird
- Bei den Bild Dateien brauchst du keine __init__.py Files in Ordnern, in denen nur Bilder gelagert sind (png Dateien)
- `reset()` Aufruf in der App muss komplett zurücksetzen, man darf dann keinen Unterschied haben ob man die App neu initialisiert hat oder zurückgesetzt hat
    - In AutoPage war das bswp. nicht der Fall, siehe Kommentar dort
    - Daher bitte nochmal durchgehen und sicherstellen dass das überall der Fall ist, das ist wichtig fürs Training um Konsitent zu sein und versteckte Fehler zu vermeiden
- Die os.path.join Statements werden leicht falsch verwendet, man nutzt da eigentlich keine Slashes, sondern macht einzelne Folder/Dateien eben als jeweils einen Parameter in dem Methodenaufruf, damit man eben keine Slashes verwenden muss (siehe auch die Kommentare, dort habe ich den richtigen Aufruf oft als Beispiel hingeschrieben)
- Du hast oft lambdas genutzt um die Methoden zu übergeben ohne sie auszuführen. Das geht auch einfacher indem du die Methode ohne Klammern angibst, dann wird sie nicht ausgeführt sondern nur übergeben, und kann später ausgeführt werden (siehe ebenfalls Kommentare dazu)
- render Methoden wurden oft in der Kindklasse überschrieben, allerdings haben sie dort keine spezielle Funktion -> die kann man denke ich löschen, habe ich auch kommentiert
- Manchmal hast du `add_widget` nur mit bestimmten Widgets aufgerufen und andere ausgelassen, ist das gewollt? (eventuell beantwortest du das in den speziellen Kommentaren dazu). Das könnte Auswirkungen auf den State Vektor haben, daher würde ich dir empfehlen das nochmal zu überprüfen

Danke für die viele Arbeit und falls du Fragen hast melde dich gerne hier oder in Slack 🙂

2023-02-25 14:04 UTC, VitoVoelker commented on naturalnets/environments/gui_app/utils.py
> +        img.shape = (height, width, 3)
Soll falls das komplette Bild ersetzt wird die Größe und Breite setzen. Wenn das nicht gemacht wird, funktioniert das slicen nicht.

2023-02-25 15:24 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/main_window_pages/settings_page.py
> +        img = super().render(img)
Ist in diesem Fall der egal weil pro PopUp ein Komplettes Bild drauf gerendert wird und nicht nur das PopUp

2023-02-25 15:36 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/auth_window_pages/login_page.py
> +        self.add_widget(self.show_pw_button)
Die Normalen Buttons haben keine State und können so nicht als Widget hinzuegfügt werden.

2023-02-25 15:50 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/home_window.py
> +                return
Falls die App sich auf der manual oder auto page befindet sollen beide Menü bereiche geprüft werden. Das ist der obere Teil. Falls sich auf einer anderen Page befinden soll nur die seitlichen Menuüpunkte geprüft werden.

2023-02-25 16:00 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/main_window_pages/auto_page.py
> +            # is manually set to 3 for the different states of the slider because this is setup before the slider is created
Der Slider kann soviele Postionen einnehmen wie beim erstellen des Sliders übergeben werden. Nur kann in der reward template irgendwie nicht die werte der Klasse übernommen werden also musste ich das manuell setzen.

2023-02-25 16:01 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/main_window_pages/manual_page.py
> +        self.add_widget(self.show_password_button)
Hat keinen State und wird deswegen nicht hinzugefügt.

2023-02-25 16:07 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/main_window_pages/manual_page.py
> +    def create_pw(self):
Genau.

2023-02-25 21:16 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/home_window.py
> +        print("Darkmode not implemented yet")
Der Darkmode ändert im Prinzip nur das aussehen deswegen ist er hier nicht implementiert.

2023-02-27 14:22 UTC, VitoVoelker commented on naturalnets/environments/passlock_app/img/crop_images.py
> +from PIL import Image
Brauch ich nochmal um Screenshots zu cropen für die kleinere App danach kann ich sie löschen.

2023-03-02 15:51 UTC, pdeubel requested changes
Danke für die vielen Änderungen! Ich habe jetzt noch folgende Sachen (nicht viel) die du noch machen musst dann können wir mergen:

- Den aktuellen main Branch reinmergen
    - Dort gibt es noch Konflikte, die bitte beheben:
    - get_screen_width/height Methoden die du neu für IGUIEnvironment hinzugefügt hast für die AnkiApp noch implementieren
    - run_app_interactive_mode hat bereits auch die AnkiConfig drin, die einfach reinmachen (sollte auch passen sie nutzt c=0)
- handle_click() in manchen Fällen returned noch None
    - Manchmal habe ich noch gesehen dass handle_click Methoden so ausgeführt werden können dass nichts returned wird (also dann None returned wird) -> Das bitte nochmal durchgehen und entsprechend anpassen, wahrscheinlich reicht es einfach ein return False am Ende der Methode anzugeben um den Default Case quasi abzufangen (weiß aber nicht ob das in jedem Fall logisch und gewollt ist, wahrscheinlich aber schon)
- In HomeWindow ist noch ein Bug, dort hast du einen Pfad mit ".png" angegeben, die Datei hat aber die Endung ".PNG"
- Ansonsten noch die neuen Kommentare durchgehen, die sind fast alle in Bezug auf das was ich hier aufgelistet habe

Danke!

2023-03-02 15:51 UTC, pdeubel commented on naturalnets/environments/passlock_app/passlock_app.py
> +        return "PasslockApp"
Nutze bitte das Klassenattribut self.window_name -> Das ist viel besser und aktuell ist das hier auch verbuggt weil die beiden Namen nicht übereinstimmen

2023-03-02 15:51 UTC, pdeubel commented on run_app_interactive_mode.py
> +                                             rescale_values(current_action[1], previous_low=0, previous_high=app.get_screen_height(), new_high=1, new_low=-1)])
Könnte man vereinfachen indem man einfach nur das vom else Block verwendet -> Das ist ja in beiden Fällen richtig

2023-03-08 11:08 UTC, merged